name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u akashllmproject --password-stdin
    - name: Build Docker image
      run: docker build -t akashllmproject/final_prediction_image:latest Code/end_point_code/.
    - name: Push Docker image
      run: docker push akashllmproject/final_prediction_image:latest
